site_name: "Bias-Variance A-Z"
site_url: https://sadatian.io/Bias-Variance-A-Z/
site_author: Dan Sadatian
site_dir: site

theme:
  name: material
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono
  palette:
    scheme: default
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true
      execute: true
      include: ["src/*.py", "src/**/*.py"]

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.plot.ly/plotly-3.7.0.min.js
  - js/code_toggle.js




extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Modules:
      - "01. Mathematical Error Decomposition": src/01_irreducible_error_and_decomposition.py
      - "02. Model Complexity & Polynomials": src/02_model_complexity_and_polynomials.py
      - "03. Learning Curves & Sample Complexity": src/03_learning_curves_and_sample_complexity.py
      - "04. Penalty-Based Control (Regularization)": src/04_regularization.py
      - "05. Cross-Validation Strategies": src/05_cross_validation_strategies.py
      - "06. Feature Selection & Dimensionality": src/06_feature_selection_and_dimensionality.py
      - "07. Aggregation & Ensembles": src/07_ensembles_bagging_and_boosting.py
      - "08. Temporally Complex Models": src/08_advanced_topics_temporally_complex_models.py
